apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - instana-agent.yaml
  - daemonset.yaml

configMapGenerator:
  - name: instana-backend-ca
    files:
    - ss-backend-cert.pem
generatorOptions:
  disableNameSuffixHash: true