apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

patches:
  - target:
      kind: QueueManager
      name: qm1
    path: native-ha-group.yaml
  - target:
      kind: QueueManager
      name: qm2
    path: native-ha-group.yaml
