apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
 
  - buildconfig.yaml
  - qm1-metrics-configuration.yaml
  - qm2-metrics-configuration.yaml
  - empty-metrics-credentials.yaml
  - deployment.yaml
  - podmonitor.yaml
  #- otel
