apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources: 
   
  - metrics
  - singleinstance-qm/
  - uniform-cluster-a/qm1
  - uniform-cluster-a/qm2
  - uniform-cluster-a/common-qm-config